name: Deploy to Docker Swarm

on:
  push:
    branches:
      - develop-AUB-41

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AUB_PRIVATE_KEY }}

      - name: Define Manager IP
        run: |
          export MANAGER_IP="98.81.234.83"  # Setze die Manager IP als Variable

      - name: Copy SQL files to EC2
        run: |
          scp -i ~/.ssh/authorized_keys ./album.sql ec2-user@$MANAGER_IP:/home/ec2-user/app/
          scp -i ~/.ssh/authorized_keys ./band.sql ec2-user@$MANAGER_IP:/home/ec2-user/app/

      - name: Copy Docker Compose file to EC2
        run: |
          scp -i ~/.ssh/authorized_keys ./docker-compose.yml ec2-user@$MANAGER_IP:/home/ec2-user/app/

      - name: Deploy to Docker Swarm
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@$MANAGER_IP << 'EOF'
            docker stack deploy --compose-file /home/ec2-user/app/docker-compose.yml my-app
          EOF
