name: Deploy to Docker Swarm

on:
  push:
    branches:
      - develop-AUB-41

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AUB_PRIVATE_KEY }}" > ~/.ssh/github_actions_key
          chmod 600 ~/.ssh/github_actions_key

      - name: Define Manager IP
        run: |
          echo "Setting Manager IP"
          export MANAGER_IP="98.81.234.83"  # Setze die Manager IP als Variable
          echo "Manager IP: $MANAGER_IP"  # Debugging-Ausgabe, um sicherzustellen, dass die IP gesetzt wurde

      - name: Copy SQL files to EC2
        run: |
          echo "Copying album.sql to $MANAGER_IP"
          scp -i ~/.ssh/github_actions_key aws/album.sql ec2-user@98.81.234.83:/home/ec2-user/app/
          echo "Copying band.sql to $MANAGER_IP"
          scp -i ~/.ssh/github_actions_key aws/band.sql ec2-user@98.81.234.83:/home/ec2-user/app/

      - name: Copy Docker Compose file to EC2
        run: |
          echo "Copying docker-compose.yml to $MANAGER_IP"
          scp -i ~/.ssh/github_actions_key ./docker-compose.yml ec2-user@98.81.234.83:/home/ec2-user/app/

      - name: Deploy to Docker Swarm
        run: |
          echo "Deploying to Docker Swarm on $MANAGER_IP"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/github_actions_key ec2-user@$MANAGER_IP << 'EOF'
            docker stack deploy --compose-file /home/ec2-user/app/docker-compose.yml my-app
          EOF
